name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      product: ${{ steps.filter.outputs.product }}
      inventory: ${{ steps.filter.outputs.inventory }}
      cart: ${{ steps.filter.outputs.cart }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            product:
              - 'product-service/**'
            inventory:
              - 'inventory-service/**'
            cart:
              - 'cart-service/**'

  test-product-service:
    needs: changes
    if: ${{ needs.changes.outputs.product == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./product-service
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Run tests
        run: npm test

  test-inventory-service:
    needs: changes
    if: ${{ needs.changes.outputs.inventory == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inventory-service
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Run tests
        run: npm test

  test-cart-service:
    needs: changes
    if: ${{ needs.changes.outputs.cart == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cart-service
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Run tests
        run: npm test
